import re

class TOONParser:
    """
    A lightweight parser for the TOON (Token-Oriented Object Notation) format
    generated by the LLVM GraphExtractor.
    
    Format Spec:
    nodes[N]{header,fields...}:
      val1,val2,...
    edges[M]{header,fields...}:
      val1,val2,...
    """
    
    def __init__(self):
        # Regex to match section headers like: nodes[100]{id,label}:
        self.header_regex = re.compile(r'(\w+)\[(\d+)\]\{([^}]+)\}:')

    def parse(self, content: str):
        """
        Parses TOON string content into a dictionary of lists.
        Returns: { "nodes": [...], "edges": [...] }
        """
        data = {}
        lines = content.strip().split('\n')
        
        current_section = None
        current_headers = []
        
        for line in lines:
            line = line.strip()
            if not line: continue
            
            # Check for section header
            match = self.header_regex.match(line)
            if match:
                section_name = match.group(1)
                # count = int(match.group(2)) # Unused validation for now
                headers_str = match.group(3)
                
                current_section = section_name
                current_headers = [h.strip() for h in headers_str.split(',')]
                data[current_section] = []
                continue
            
            if current_section:
                values = line.split(',')
                
                row = {}
                for i, h in enumerate(current_headers):
                    if i < len(values):
                        row[h] = values[i].strip()
                
                data[current_section].append(row)
                
        return data

    def parse_file(self, filepath: str):
        with open(filepath, 'r') as f:
            return self.parse(f.read())

